### ISSUE TITLE
[FEATURE] Possibility to add and remove quantity in an item 

### ISSUE THREAD

**Issue by DylanP97** [DylanP97/native-sakurahouse#1]
Enhance the user experience by adding the ability to adjust the quantity of items within the shopping cart.
Users will be able to incrementally increase or decrease the quantity of a specific item with ease on the MenuScreen.

By implementing this feature, we provide a more intuitive and flexible shopping experience, allowing users to update each product quantity.

Take Inspiration on the McDonald's Kiosk:
https://www.behance.net/gallery/84835219/McDonalds-Kiosk-Redesign

**Comment by DylanP97** [comment]
I would love too

I'm trying to inspire myself from this McDonalds kiosk design 
https://www.behance.net/gallery/84835219/McDonalds-Kiosk-Redesign

Please make a new fresh branch and then a PR

**Comment by DylanP97** [comment]
Hello,
When you think you will PR

**Comment by Krunal-Karena** [comment]
in 2-3 days.

**Comment by DylanP97** [comment]
Alright awesome 
Just a note, because I'm currently updating the project so please follow the latest commit 
Thanks so much ;)

**Comment by Krunal-Karena** [comment]
hello bro! Your app is not working in my laptop
![image](https://github.com/DylanP97/native-sakurahouse/assets/99881021/fe299319-03b5-4fdf-a7f9-b8683ac081d9)
it's giving 👆 errors.

**Comment by DylanP97** [comment]
Hello,
Did you tried to launched it with Expo Go app ?

I usually make npm start, then scan the QR code

![Screenshot_2023-10-13-00-07-31-511-edit_com miui home](https://github.com/DylanP97/native-sakurahouse/assets/104037055/9df52a21-865f-4560-b4e6-9b2ec9ad0fa3)

**Comment by Krunal-Karena** [comment]
i tried but it's also not working in Expo Go.

**Comment by DylanP97** [comment]
- npm start at the root of the project
- then scan with the Expo Go app the QR Code

Is there an error message or some indications ?

**Comment by Krunal-Karena** [comment]
![image](https://github.com/DylanP97/native-sakurahouse/assets/99881021/b2f41656-f30c-4ed2-9fe7-8c3f81001b22)

Android Bundling failed 
Unable to resolve "../components/Loading" from "screens\HomeScreen.js"

**Comment by DylanP97** [comment]
It is working on my side 

Please clone the latest commit
https://github.com/DylanP97/native-sakurahouse
