### ISSUE TITLE
implement redux to create global order store

### ISSUE THREAD

**Issue by DylanP97** [DylanP97/native-sakurahouse#5]
The goal is to create a store throughout the application that will contain all order informations such as the location, the items, their selected quantity, the total amount of the order 

You will need to also implement the ordering logic, to add and remove items from the basket or increase/reduce their quantities

**Comment by sanketyelave** [comment]
Hey I can work on it and also will try to give the PR asap . can you assign it to me

**Comment by DylanP97** [comment]
Hello,
Okay, I already started implement Redux but you can complete the process of ordering to finish the implementation

**Comment by DylanP97** [comment]
Let me know if you have any question ;)

**Comment by DylanP97** [comment]
Anything new ?
